services:
  - type: web
    name: taha-s-helper-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: POLLINATIONS_API_KEY
        sync: false
